"""For each prompt, retrieve the 2 most similar COCO images for the images
generated by Stable Diffusion v1.5 and v2.1, using CLIP and DINO embeddings.

Run from the repository root:
    python scripts/retrieve_similar_images.py

Requires the embeddings created by dataset_embedding_extraction.py and
generated_images_embedding_extraction.py.
"""

import json
import os

import torch
from tqdm import tqdm

from utils import find_top_matches

PROMPTS_PATH = "data/prompts.txt"
OUTPUT_PATH = "results/retrieved_similar_images.json"

# Dataset embeddings (COCO images)
clip_dataset_embeds = torch.load("embeddings/clip_embeddings.pt")
dino_dataset_embeds = torch.load("embeddings/dino_embeddings.pt")

# Embeddings of the generated images, per Stable Diffusion version
clip_embeds_v1 = torch.load("embeddings/clip_embeddings_v1-5.pt")
clip_embeds_v2 = torch.load("embeddings/clip_embeddings_v2-1.pt")
dino_embeds_v1 = torch.load("embeddings/dino_embeddings_v1-5.pt")
dino_embeds_v2 = torch.load("embeddings/dino_embeddings_v2-1.pt")

# Name of each result -> (embeddings of generated images, dataset embeddings to search)
experiments = {
    "clip_v1-5": (clip_embeds_v1, clip_dataset_embeds),
    "clip_v2-1": (clip_embeds_v2, clip_dataset_embeds),
    "dino_v1-5": (dino_embeds_v1, dino_dataset_embeds),
    "dino_v2-1": (dino_embeds_v2, dino_dataset_embeds),
}

with open(PROMPTS_PATH, "r") as f:
    prompts = [line.strip() for line in f.readlines() if line.strip()]

results = {}

for i, prompt in enumerate(tqdm(prompts)):
    key = f"{i + 1:02d}_{prompt}"
    image_name = f"{key}.png"  # generated image file, named after its prompt
    results[key] = {}

    for name, (generated_embeds, dataset_embeds) in experiments.items():
        if image_name not in generated_embeds:
            raise KeyError(f"No embedding found for '{image_name}' in {name}")
        query = generated_embeds[image_name].unsqueeze(0)
        results[key][name] = find_top_matches(query, dataset_embeds)

os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
with open(OUTPUT_PATH, "w") as f:
    json.dump(results, f, indent=2)

print(f"Retrieval complete. Results saved to {OUTPUT_PATH}")